[network]
name = "testnet"
stacks_node_rpc_address = "https://api.testnet.hiro.so"
deployment_fee_rate = 10

[accounts.deployer]
mnemonic = "robust base laugh bronze put twice talk deposit shaft dish oil hawk security govern mutual alone kid eternal federal only spread boring suggest riot"
